//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIUB_GamingFest_fatema.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class finaltermEntities1 : DbContext
    {
        public finaltermEntities1()
            : base("name=finaltermEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<game> games { get; set; }
        public virtual DbSet<manager> managers { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<volunteer> volunteers { get; set; }
    }
}
